### ISSUE TITLE
Failures to copy to clipboard silently fail

### ISSUE THREAD

**Issue by conradkleinespel** [conradkleinespel/rooster#10]
When Rooster does not succeed in copying a password to the clipboard, the user is currently not notified of the failure, which can be confusing. @maxjacobson talked about this in #9 and it's an interesting question.

> The one thing I'm wondering is whether rooster should notify the user
> that something went wrong during the copying so they can attempt to fix
> it. What do you think?

Some failures are reported by `rust-clipboard`, for instance if you are on a platform that `rust-clipboard` does not support. Other failures are silently ignored.

If you are willing to work on fixing this, feel free to tell us about yourself here and we'll help you get started. The basic idea would be to improve the error handling in `src/command/*.rs` files, for instance here:
https://github.com/conradkleinespel/rooster/blob/d5d5f9f3895a8fe65313da0a972e5d6f6753ec4c/src/commands/add.rs#L63

@maxjacobson how would you like to have been notified when you encountered this bug ?

**Comment by maxjacobson** [comment]
The reason copying failed for me is arguably a bit obscure. When running `tmux` after upgrading to the new macOS Sierra, all kinds of clipboard integrations stopped working. There's a configuration workaround to fix it, but it affects stock tmux configuration and so I suspect it might affect other potential rooster users going forward as well. And, of course, other things could come up over the long and hard course of life.

In my case, it would've been cool if rooster somehow magically knew what went wrong and told me to go update my tmux configuration. I don't think it should actually do that, of course, because rooster is a password manager and not a database of bugs in the interaction between all operating systems and other projects.

So, more realistically, I think I would have preferred if the experience was something like this:

First, actual current behavior:

```
$ rooster generate github maxjacobson
Alright! Here is your password: KSt0pp032B3E@\+;-\;i>9.GK{5G6XeH
```

Desired behavior:

```
$ rooster generate github maxjacobson
Hmm, we tried to copy the new password to your clipboard, but something went wrong. Don't worry, it's saved, and you can see it with `rooster get github --show` or `rooster get github -s`.
```

The benefits in my opinion:

1. doesn't print the password to the screen (normally rooster only does this when you specifically ask it to, and I think that's a behavior worth preserving in case people are concerned about someone looking at their screen or something)
2. let's the user know something went wrong, which in some cases (like mine) is a solve-able problem

Even better would be if it could print any details about what specifically went wrong, but I'm not sure what information rooster has about that.

**Comment by conradkleinespel** [comment]
@maxjacobson Your suggested fix with the exact message you wrote sounds good to me and both of your points make sense to me.

I'm not sure how we could know what went wrong. I think this kind of thing should be fixed during installation, by having a proper install script, instead of building a database of bugs, as you say.

On Ubuntu, for some reason, I have to build `rooster-clipboard` with `cargo build` and `rooster` with `cargo build --release`. Otherwise, copying to the clipboard does not work... I don't know why the copy works in debug mode and not in release mode. And the weirdest thing is that `rust-clipboard` thinks that the copy works in release mode even though it doesn't. Must be something related to `X`. I wasn't able to find the cause of this bug.
