### ISSUE TITLE
Wayland Clipboard

### ISSUE THREAD

**Issue by travankor** [conradkleinespel/rooster#51]
Linux and some other Unix-like systems are replacing the X11 display protocol with the new [Wayland](https://wayland.freedesktop.org/architecture.html) protocol.

There is a safe Rust [crate](https://github.com/YaLTeR/wl-clipboard-rs) for working with the Wayland clipboard. Currently, [wlroots](https://github.com/swaywm/wlroots) compositors are the best-supported, but other compositors are encouraged to use their portable Wayland clipboard extension.

**Comment by conradkdotcom** [comment]
@travankor Thanks ! I think this might be a good fit. Unfortunately, the referenced crate has more than 15 dependencies. The thing is, I review every line of source code I include as a dependency in Rooster. Unfortunately, I don't have time to review these 15 crates at the moment.

The current setup uses `xsel` or `xclip` and works well. It's advantage is that it relies on the packages available in the users system package manager, which means less work for me because I don't need to review dozens of dependencies: I trust the tried and tested UNIX tools commonly available on Linux distributions. For Wayland, I see that there is `wl-clipboard` (https://github.com/bugaevc/wl-clipboard) that seems available on Linux distributions (at least it is available on Arch Linux, which I use). So I might integrate that at some point. It'll be simple and secure.

Until then, I encourage anyone who needs Wayland support to open a PR which adds support for Wayland through `wl-clipboard`. I will be happy to review it!

**Comment by conradkleinespel** [comment]
@travankor  Without further feedback, I'll go ahead and close this issue. If someone else reads this and needs Wayland support, feel free to open a PR as described above or reply to the conversation here. Cheers !

**Comment by conradkleinespel** [comment]
@travankor This is now done, thanks @kamiyaa for #60
